version: "3.8"

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      CHROMA_SERVER_HOST: 0.0.0.0
      CHROMA_SERVER_HTTP_PORT: 8000
      CHROMA_SERVER_CORS_ALLOW_ORIGINS: "*"
      CHROMA_DB_IMPL: "duckdb" # você pode trocar para "clickhouse" se quiser
      CHROMA_PERSIST_DIRECTORY: /chroma/data
    volumes:
      - ./chroma-data:/chroma/data
    restart: unless-stopped
